# This file may be used to create an environment using:
# conda env create -f environment.yml
name: poli-sci-kit-dev
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pytest
  - scipy
  - numpy
  - pandas
  - seaborn
  - stdviz
